#! /usr/bin/env python3
#
# storage_tutorial.py
#
"""
Tutorial on how to use RocksStorageNode to save selectively save
individual Atoms or entire AtomSpaces to disk. This is a fairly basic
demo; the scheme files in this directory provide a larger variety of
examples. As the scheme examples are written in a direct fashion, it
should be fairly obvious how to port those examples to Python, as
desired.
"""

# Boilerplate
from opencog.atomspace import AtomSpace
from opencog.type_constructors import *
from opencog.storage_rocks import *

# AtomSpace cne be given a name; if not supplied, one is autogenerated.
space = AtomSpace("my basic space")
set_thread_atomspace(space)

# Basic Atomese tutorial: a labelled directed graph edge.
# In ASCII graphics:
#
#                      "some edge label"
#    "from vertex" ------------------------> "to vertex"
#
# which in Atomese, becomes
#
#    (Edge (Predicate "some edge label")
#            (List (Item "from vertex") (Item "to vertex")))
#
# and for python, the parens get re-arranged and commas are inserted:
#
#    Edge (Predicate ("some edge label"),
#          List (Item ("from vertex"), Item ("to vertex")))
#
e = EdgeLink(
	PredicateNode("My collection of URLs"),
	ListLink(
		ItemNode("file:///Home Computer/folders/My photo album"),
		ItemNode("Fantastic Sunset on Sunday.jpg")))

print("Here's your data:", e)

# -------------------------------------------
# AtomSpace contents can be stored and loaded from disk, and sent over
# the net (to other AtomSpaces). All such operations use exactly the
# same API, given by the StorageNode. This demo illustrates the API by
# using it with RocksStorageNode, which is built on top of the RocksDB
# disk database.  Rocks is nice, because it requires no config to use.

# Create a RocksDB StorageNode.
# The rocks:// URL specifies a directory in the local filesystem.
storage = RocksStorageNode("rocks:///tmp/foo")

# Open a connection to storage using message-passing.
# The StorageNode API works by sending messages to StorageNodes via
# set_value(). All messages are PredicateNodes naming the operation.
space.set_value(storage, PredicateNode("*-open-*"), VoidValue())
print("Opened connection to storage")

# Store the one and only edge created above.
space.set_value(storage, PredicateNode("*-store-atom-*"), e)
print("Stored the edge")

# Close the connection to storage.
space.set_value(storage, PredicateNode("*-close-*"), VoidValue())
print("Closed the connection to storage")

# -------------------------------------------
# The rest of this demo is about restoring the Atom that was just saved.
# To prove that this works, the AtomSpace will be cleared. To prove that
# it was cleared, look at the contents before and after.

# Define a utility printer
def prt_atomspace_contents(asp) :
	print("AtomSpace contains a total of " + str(len(asp)) + " Atoms")
	if 0 < len(asp) :
		print("These are:")
	count = 0
	for atom in asp:
		count += 1
		print("Atom " + str(count) + ".... " + str(atom))

print("The AtomSpace before clearing:")
prt_atomspace_contents(space)

print("\nWill now clear the AtomSpace.")
space.clear()
print("The AtomSpace size after clearing: ", len(space))
prt_atomspace_contents(space)

# -------------------------------------------
# The clear clobbers the StorageNode; create it again.
storage = RocksStorageNode("rocks:///tmp/foo")
space.set_value(storage, PredicateNode("*-open-*"), VoidValue())
print("Reopened connection to storage")

# -------------------------------------------
# Restore one atom: the predicate, whose name we magically know already.
# The fetch-atom message requires a LinkValue containing the AtomSpace
# and the atom to fetch.
print("Restore one atom: the predicate, whose name we magically know already.")
url_pred = PredicateNode("URL")
space.set_value(storage, PredicateNode("*-fetch-atom-*"),
	LinkValue([space, url_pred]))
prt_atomspace_contents(space)

# Restore all Edges in storage by fetching the incoming set.
print("Restore all Edges in storage.")
space.set_value(storage, PredicateNode("*-fetch-incoming-set-*"),
	LinkValue([space, url_pred]))

# Close the connection to storage.
space.set_value(storage, PredicateNode("*-close-*"), VoidValue())

print("After restoring, the AtomSpace size is " + str(len(space)))
prt_atomspace_contents(space)

print("Good bye!")
#
# The StorageNode API works via message-passing. Messages that have
# mandatory arugments are sent by saying
#
#    `atomspace.set_value(storage, message, args)`.
#
# A small handfule of messages do not require arguments; these work by
# saying
#
#    result = `atomspace.get_value(storage, message)`.
#
# Messages are always PredicateNodes naming the operation.
# Common messages:
#
# * `*-open-*` and `*-close-*` to open/close storage connections.
#   Args: VoidValue()
#
# * `*-store-atom-*` to store an atom and all its values.
#   Args: the atom to store
#
# * `*-fetch-atom-*` to fetch an atom and all its values.
#   Args: LinkValue([atomspace, atom])
#
# * `*-store-atomspace-*` and `*-load-atomspace-*` for bulk operations.
#   Args: the AtomSpace
#
# * `*-fetch-incoming-set-*` to fetch all links containing an atom.
#   Args: LinkValue([atomspace, atom])
#
# * `*-fetch-incoming-by-type-*` to fetch links of a specific type.
#   Args: LinkValue([atomspace, atom, TypeNode("EdgeLink")])
#
# * `*-store-value-*` and `*-fetch-value-*` for individual values.
#   Args: LinkValue([atom, key])
#
# * `*-update-value-*` performs an atomic read-modify-write (increment).
#   Args: LinkValue([atom, key, delta])
#
# * `*-delete-*` and `*-delete-recursive-*` to remove atoms from storage.
#   Args: LinkValue([atomspace, atom])
#
# * `*-barrier-*` for multi-thread synchronization.
#   Args: atomspace
#
# * `*-connected?-*` to check connection status.
#   Use: atomspace.get_value(storage, PredicateNode("*-connected?-*"))
#
# * `*-monitor-*` to get performance/debugging info.
#   Use: atomspace.get_value(storage, PredicateNode("*-monitor-*"))
#
# See https://wiki.opencog.org/w/StorageNode for API documentation and
# longer description of the messages. A complete list of messages for
# a given StorageNode can be optained by saying
#
#     storage.getMessages()
#
# THE END.
# ---------------------------------------------------------------------
